name: Monitor Zulip Issues by alya

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  monitor-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Issues from Zulip Repository
      id: fetch-issues
      env:
        ZULIP_TOKEN: ${{ secrets.ZULIP_TOKEN }}
      run: |
        # Get current time of the host machine
        CURRENT_TIME=$(date)

        # Fetch issues from the Zulip repository using the API
        curl -s -H "Authorization: Bearer $ZULIP_TOKEN" \
          https://api.github.com/repos/zulip/zulip/issues > issues.json

        # Filter issues created by the user 'alya'
        jq -r '.[] | select(.user.login == "alya") | .html_url' issues.json > filtered_issues.txt

        # Output the results for use in later steps
        if [ -s filtered_issues.txt ]; then
          echo "Found issues by alya:"
          cat filtered_issues.txt
          echo "::set-output name=issues::$(cat filtered_issues.txt)"
        else
          echo "No issues by alya found."
          echo "::set-output name=issues::"
        fi

    - name: Send Email Notification
      if: ${{ steps.fetch-issues.outputs.issues != '' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "New Issues by alya in Zulip Repository"
        body: |
          The following issues were created by alya in the Zulip repository:
          ${{ steps.fetch-issues.outputs.issues }}

          Current time on the host machine: $CURRENT_TIME
        to: ronaksingh2708@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
